!pip install Pillow

from PIL import Image

No_of_screenshots = 180;#0 to 179 automatically generated by windows 11 on each print screen
# Each of this screenshot Windows 11 automatically index

filename = [None] * No_of_screenshots ;
image    = [None] * No_of_screenshots ;
image_converted = [None] * No_of_screenshots ;

image_list = [None];

for number in range(No_of_screenshots):
 
    filename[number] =  'C:\python_trials\\2022-02-01 (' + str(number) + ').png'
    #print(filename[number])     
   
    image[number] = Image.open(filename[number]);
    
    image_converted[number] = image[number].convert('RGB')
    
    image_list.append(image_converted[number])
    
    
im1 = image_converted[0]

im1_others = image_converted[1:No_of_screenshots-1]

im1.save(r'C:\python_trials\ScreenShots.pdf',save_all=True, append_images = im1_others)
